# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVLmu2oJbDjv6lqEu0K4B8yirf_w4jsF
"""

# =====================================================
# STEP 1: Install dependencies
# =====================================================
!pip install tensorflow opencv-python seaborn

import os, zipfile, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# =====================================================
# STEP 2: Extract dataset
# =====================================================
zip_path = "/content/archive (1).zip"   # Upload your archive.zip here
extract_path = "/content/data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

dataset_dir = os.path.join(extract_path, os.listdir(extract_path)[0])
print("Dataset folder:", dataset_dir)

# =====================================================
# STEP 3: Setup Generators (memory-safe)
# =====================================================
image_size = 224
batch_size = 16

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=15,
    zoom_range=0.1,
    horizontal_flip=True
)

train_gen = datagen.flow_from_directory(
    dataset_dir,
    target_size=(image_size, image_size),
    batch_size=batch_size,
    class_mode="categorical",
    subset="training"
)

val_gen = datagen.flow_from_directory(
    dataset_dir,
    target_size=(image_size, image_size),
    batch_size=batch_size,
    class_mode="categorical",
    subset="validation",
    shuffle=False
)

class_names = list(train_gen.class_indices.keys())
print("Classes:", class_names)

# =====================================================
# STEP 4: Build Model (MobileNetV2)
# =====================================================
base_model = MobileNetV2(weights="imagenet", include_top=False,
                         input_tensor=Input(shape=(image_size, image_size, 3)))
base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)
x = Dense(128, activation="relu")(x)
output = Dense(len(class_names), activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)
model.compile(optimizer=Adam(learning_rate=1e-4),
              loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()

# =====================================================
# STEP 5: Train (lighter on RAM)
# =====================================================
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10
)

# =====================================================
# STEP 6: Plot Results
# =====================================================
plt.plot(history.history['accuracy'], label="Train Acc")
plt.plot(history.history['val_accuracy'], label="Val Acc")
plt.legend(); plt.title("Accuracy"); plt.show()

plt.plot(history.history['loss'], label="Train Loss")
plt.plot(history.history['val_loss'], label="Val Loss")
plt.legend(); plt.title("Loss"); plt.show()

# =====================================================
# STEP 7: Evaluation
# =====================================================
val_gen.reset()
y_true = val_gen.classes
y_pred = np.argmax(model.predict(val_gen), axis=1)

print(classification_report(y_true, y_pred, target_names=class_names))

cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted"); plt.ylabel("True"); plt.title("Confusion Matrix"); plt.show()

# =====================================================
# STEP 8: Predict on uploaded image
# =====================================================
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
    img = load_img(fn, target_size=(image_size, image_size))
    arr = img_to_array(img) / 255.0
    arr = np.expand_dims(arr, axis=0)

    preds = model.predict(arr)[0]
    idx = np.argmax(preds)
    confidence = preds[idx]

    print(f"Prediction for {fn}: {class_names[idx]} ({confidence:.2f})")

# =====================================================
# STEP 9: Predict from Camera (Colab)
# =====================================================
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
from PIL import Image
import io

def take_photo(filename="photo.jpg", quality=0.8):
    js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      div.appendChild(video);

      document.body.appendChild(div);
      const stream = await navigator.mediaDevices.getUserMedia({video: true});
      video.srcObject = stream;
      await video.play();
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getTracks().forEach(track => track.stop());
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

# Capture & Predict
image_path = take_photo()
img = load_img(image_path, target_size=(image_size, image_size))
arr = img_to_array(img) / 255.0
arr = np.expand_dims(arr, axis=0)

preds = model.predict(arr)[0]
idx = np.argmax(preds)
confidence = preds[idx]
print(f"Camera Prediction: {class_names[idx]} ({confidence:.2f})")

# ==========================
# UPLOAD & PREDICT (standalone)
# ==========================
from google.colab import files
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

# Upload one or more images
uploaded = files.upload()

for fn in uploaded.keys():
    img = load_img(fn, target_size=(image_size, image_size))  # reuse same size
    arr = img_to_array(img) / 255.0
    arr = np.expand_dims(arr, axis=0)

    preds = model.predict(arr)[0]
    idx = np.argmax(preds)
    confidence = preds[idx]

    print(f"Prediction for {fn}: {class_names[idx]} ({confidence:.2f})")

# ==========================
# CAMERA CAPTURE & PREDICT (standalone)
# ==========================
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

def take_photo(filename="photo.jpg", quality=0.8):
    js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      div.appendChild(video);

      document.body.appendChild(div);
      const stream = await navigator.mediaDevices.getUserMedia({video: true});
      video.srcObject = stream;
      await video.play();
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getTracks().forEach(track => track.stop());
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

# Capture from camera
image_path = take_photo()

# Preprocess and predict
img = load_img(image_path, target_size=(image_size, image_size))
arr = img_to_array(img) / 255.0
arr = np.expand_dims(arr, axis=0)

preds = model.predict(arr)[0]
idx = np.argmax(preds)
confidence = preds[idx]

print(f"Camera Prediction: {class_names[idx]} ({confidence:.2f})")

from google.colab import files
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np


print("Upload multiple images for prediction...")
uploaded = files.upload()


images, filenames = [], []
for fn in uploaded.keys():
    img = load_img(fn, target_size=(image_size, image_size))  # use same input size as training
    arr = img_to_array(img) / 255.0
    images.append(arr)
    filenames.append(fn)


images = np.array(images)


preds = model.predict(images)

for i, p in enumerate(preds):
    idx = np.argmax(p)
    confidence = p[idx]
    print(f"{filenames[i]} --> {class_names[idx]} ({confidence:.2f})")